import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/components/Providers'
import AppBar from '@/components/AppBar'
import { Toaster, toast } from 'sonner'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es-AR">
      <body className={inter.className}>
        <Providers>
          <AppBar />
          <main className='min-h-screen flex items-center justify-center'>
            {children}
          </main >
          <footer>
            <p className='bg-slate-900 p-4 flex justify-center'>Copyright 2023-Arturo Gabriel Ramirez</p>
          </footer>
        </Providers>
      </body>
    </html>
  )
}